models/Marcadores.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "marcadores".
 *
 * @property int $id
 * @property string $nombre
 * @property string $descripcion
 */
class Marcadores extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'marcadores';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nombre','descripcion','tipo','url'], 'string', 'max' => 255],
            [['descripcionl'], 'string', 'max' => 600],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nombre' => 'Nombre',
            'descripcion' => 'Descripcion',
            'descripcionl'=> 'Descripcion Larga',
            'tipo'=> 'Tipo',
            'url'=> 'Url'
        ];
    }

    /**
     * @inheritdoc
     * @return MarcadoresQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new MarcadoresQuery(get_called_class());
    }
}

controllers/MarcadoresController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Marcadores;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * MarcadoresController implements the CRUD actions for Marcadores model.
 */
class MarcadoresController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Marcadores models.
     * @return mixed
     */
    public function actionIndex($id=0)
    {
        
        $modelo=Marcadores::findOne(['id'=>$id]);
        
        $dataProvider = new ActiveDataProvider([
            'query' => Marcadores::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'datos'=>$modelo,
        ]);
    }
    
     public function actionPublicos(){
        $modelo=Marcadores::findOne(['id'=>$id]);
        
        $dataProvider = new ActiveDataProvider([
            'query' => Marcadores::find()->where([
                'tipo'=>'publico'
            ]),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'datos'=>$modelo,
        ]);
    }
    
    public function actionAdmin(){
        $modelo=Marcadores::findOne(['id'=>$id]);
        
        $dataProvider = new ActiveDataProvider([
            'query' => Marcadores::find(),
        ]);

        return $this->render('admin', [
            'dataProvider' => $dataProvider,
            'datos'=>$modelo,
        ]);
        
    }

    /**
     * Displays a single Marcadores model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['admin', 'id' => $model->id]);
        }

        return $this->render('modificar', [
            'model' => $model,
        ]);
    }

    /**
     * Creates a new Marcadores model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Marcadores();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['admin']);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Marcadores model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Marcadores model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Marcadores model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Marcadores the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Marcadores::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
    
   
}

views/marcadores/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Marcadores */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="marcadores-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'nombre')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'descripcion')->textInput(['maxlength' => true]) ?>
    
    <?= $form->field($model, 'descripcionl')->textInput(['maxlength' => true]) ?>
    
    <?= $form->field($model, 'tipo')->dropDownList(['publico' => 'publico', 'privado'=>'privado']) ?>
    
    <?= $form->field($model, 'url')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton('Guardar', ['class' => 'btn btn-success col-lg-offset-11']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/marcadores/_registro.php
<?php
use yii\bootstrap\Modal;
?>

<div class="celdas col-lg-4">
    <?=$model->id ?>
</div>
<div class="celdas col-lg-4">
    <a href="<?=$model->url?>">
        <?= $model->descripcion ?>
    </a>
</div>
<div class="celdas col-lg-4">
<?php
    Modal::begin([
    'header' => '<h2>Descripcion del Enlace </h2>',
    'toggleButton' => [
        'label' => $model->descripcion,
        'class' => 'btn'
    ],
]);

echo $model->descripcionl;

Modal::end();
?>
</div>

views/marcadores/admin.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */
?>
<div class="marcadores-index">
    <?=
    GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            'id',
            [
                'attribute' => 'nombre',
                'format' => 'html',
                'value' => function ($model) {
                    return Html::a($model->nombre, ['marcadores/view', 'id' => $model->id], ['class' => 'profile-link']);
                },
            ],
            [
                'attribute' => 'descripcion',
                'format' => 'html',
                'value' => function ($model) {
                    return Html::a($model->descripcion, ['marcadores/index', 'id' => $model->id], ['class' => 'profile-link']);
                },
            ],
        ],
        'summary' => false,
    ]);
    ?>

</div>

<p>
    <?= Html::a('Nuevo',['create'],['class' =>'btn btn-success col-lg-offset-11'])?>
</p>

views/marcadores/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Marcadores */

$this->title = 'Añadir Marcador';
$this->params['breadcrumbs'][] = ['label' => 'Marcadores', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="marcadores-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/marcadores/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\ListView;
use yii\bootstrap\Modal;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */
?>
<div class="marcadores-index">



    <?=
    GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            'id',
            [
                'attribute' => 'nombre',
                'format' => 'html',
                'value' => function ($model) {
                    return '<a href="' . $model->url . '">' . $model->nombre . '</a>';
                },
            ],
            [
                'attribute' => 'descripcion',
                'format' => 'html',
                'value' => function ($model) {
                    return Html::a($model->descripcion, ['marcadores/index', 'id' => $model->id], ['class' => 'profile-link']);
                },
            ],
        ],
        'summary' => false,
    ]);
    ?>
<!-- Otra forma de mostrar el listado con ListView
    <div class="row table-bordered listado">
    <?
     echo   ListView::widget([
            'dataProvider' => $dataProvider,
            'itemView' => '_registro',
            'summary' => false
        ]);
        ?>
   </div>-->


</div>

<?php
if($datos){
        Modal::begin([
                        'header' => '<h2>Descripcion del Enlace </h2>',
//                        'toggleButton' => [
//                            'label' => $datos->descripcion,
//                            'class' => 'btn'
//                        ],
                    'clientOptions'=>['show'=>'true'],
                    ]);

                    echo $datos->descripcionl;
?>
<div class="row">
    <div class="col-lg-offset-8 col-lg-2">
<a href="<?=$datos->url?>" class="btn btn-info" target="_blank">Visitar</a>
</div>
<div class="col-lg-2">
<?= Html::a("Cerrar", ['marcadores/index'], ['class' => 'btn btn-info'])?>

</div></div>
<?php
    Modal::end();
}
?>

views/marcadores/modificar.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Marcadores */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="marcadores-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'nombre')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'descripcion')->textInput(['maxlength' => true]) ?>
    
    <?= $form->field($model, 'descripcionl')->textInput(['maxlength' => true]) ?>
    
    <?= $form->field($model, 'tipo')->dropDownList(['publico' => 'publico', 'privado'=>'privado']) ?>
    
    <?= $form->field($model, 'url')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton('Guardar', ['class' => 'btn btn-success col-lg-offset-10']) ?>
         <?= Html::a('Eliminar', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Seguro que quieres eliminar este elemento?',
                'method' => 'post',
            ]])?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/marcadores/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Marcadores */

$this->title = 'Actualizar Marcadores: {nameAttribute}';
$this->params['breadcrumbs'][] = ['label' => 'Marcadores', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="marcadores-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/marcadores/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Marcadores */


$this->params['breadcrumbs'][] = ['label' => 'Marcadores', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="marcadores-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Guardar', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Eliminar', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Seguro que quieres eliminar este elemento?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'nombre',
            'descripcion',
            'descripcionl',
            'tipo',
            'url'
        ],
    ]) ?>

</div>